package com.elice.team6backspring.controller;

import com.elice.team6backspring.domain.Recipe;
import com.elice.team6backspring.dto.RecipeRequest;
import com.elice.team6backspring.repository.RecipeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller	// This means that this class is a Controller
@RequestMapping(path="/recipes") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private RecipeRepository recipeRepository;

	@PostMapping
	public @ResponseBody Recipe addNewRecipe (@RequestBody RecipeRequest request) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Recipe recipe = request.convertRecipe();

		Recipe newRecipe = recipeRepository.save(recipe);
		return newRecipe;
	}

	@PatchMapping(path="/{id}")
	public @ResponseBody String patchRecipe (@PathVariable("id")  Integer recipeId, @RequestBody RecipeRequest request) {

		Recipe recipe = recipeRepository.findOneByRecipeId(recipeId);
		Recipe updateRecipe = recipe.of(request);

		recipeRepository.save(updateRecipe);
		return "saved!";
	}

	@GetMapping
	public @ResponseBody Iterable<Recipe> getAllRecipes() {
		// This returns a JSON or XML with the users
		return recipeRepository.findAll();
	}

	@GetMapping(path="/{id}")
	public @ResponseBody Recipe getRecipe(@PathVariable("id") Integer recipeId) {
		// This returns a JSON or XML with the users
		return recipeRepository.findOneByRecipeId(recipeId);
	}

	@DeleteMapping(path="/{id}")
	public @ResponseBody String removeRecipe(@PathVariable("id") Integer recipeId) {
		// This returns a JSON or XML with the users
		Recipe recipe = recipeRepository.getReferenceById(recipeId);
		recipeRepository.deleteById(recipeId);

		return recipe.getRecipeName()+" is removed";
	}
}
